name: bp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - bwa
  - samtools[version='>=1.10']
  - bcftools
  - bedtools
  - vcftools
  - sambamba
  - vt=0.57721
  - picard
  - gatk
  - gatk4
  - root
  - pwwang::yeppp
#  - ucsc-fetchchromsizes
#  - ucsc-bigwigaverageoverbed
#  - ucsc-wigtobigwig
#  - ucsc-liftover
  - scipy
  - numpy
  - pandas
  - awscli
  - synapseclient
  - statsmodels
  - rpy2
  - pysam
  - pysamstats
  - pyfaidx
  - regex
  - r-rcolorbrewer
  - r-ggplot2
  - r-paramhelpers
  - r-devtools
  - r-randomforest
  - r-e1071
  - r-nnet
  - r-mlr
  - r-xml
  - r-glmnet
  - r-caret
