channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3
  - root
  - bwa
  - samtools[version='>=1.10']
  - bcftools
  - bedtools
  - vcftools
  - sambamba
  - vt=0.57721
  - picard
  - gatk
  - gatk4
  - ucsc-fetchchromsizes
  - ucsc-bigwigaverageoverbed
  - ucsc-wigtobigwig
  - ucsc-liftover
  - scipy
  - numpy
  - pandas
  - pysam
  - pysamstats
  - pyfaidx
  - regex
  - r-rcolorbrewer
  - r-ggplot2
  - r-paramhelpers
  - r-devtools
  - r-randomforest
  - r-e1071
  - r-nnet
  - r-mlr
  - r-xml
  - r-glmnet
  - r-caret
  - pwwang::yeppp
